import Program from '.';
import { parseInputString } from '../utils';

describe('Part 1', () => {
    let program: Program;

    beforeEach(() => {
        program = new Program();
    });

    it('should return 14', () => {
        const output = program.runPart1(parseInputString(`
            ............
            ........0...
            .....0......
            .......0....
            ....0.......
            ......A.....
            ............
            ............
            ........A...
            .........A..
            ............
            ............
        `));

        expect(output).toEqual(14);
    });
});

describe('Part 2', () => {
    let program: Program;

    beforeEach(() => {
        program = new Program();
    });

    it('should return 9', () => {
        const output = program.runPart2(parseInputString(`
            T.........
            ...T......
            .T........
            ..........
            ..........
            ..........
            ..........
            ..........
            ..........
            ..........
        `));

        expect(output).toEqual(9);
    });

    it('should return 34', () => {
        const output = program.runPart2(parseInputString(`
            ............
            ........0...
            .....0......
            .......0....
            ....0.......
            ......A.....
            ............
            ............
            ........A...
            .........A..
            ............
            ............
        `));

        expect(output).toEqual(34);
    });
});
